"""Project-local guard for Mistral OCR free-tier usage.

The Mistral account page exposes an organization-wide allowance, but this
project cannot see usage generated by other applications in the same
organization.  This module therefore implements a conservative, project-local
page reservation ledger.  Reservations happen before the first secondary OCR
request and are never rolled back on failure.
"""

from __future__ import annotations

import json
import math
import threading
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Optional

from pdf2epub.workflow_contracts import atomic_write_text


LEDGER_SCHEMA_VERSION = 1
DEFAULT_MONTHLY_ALLOWANCE_USD = 10.0
DEFAULT_OCR_PRICE_PER_1000_PAGES_USD = 4.0
DEFAULT_SAFETY_MARGIN_USD = 0.5
DEFAULT_USAGE_LEDGER = "mistral_usage.json"

_LEDGER_LOCK = threading.Lock()


class MistralBudgetExceeded(RuntimeError):
    """Raised when a secondary OCR request would exceed the local free-tier cap."""


def _mistral_settings(config: Mapping[str, Any]) -> dict[str, Any]:
    ocr = config.get("ocr", {}) if isinstance(config, Mapping) else {}
    backends = ocr.get("backends", {}) if isinstance(ocr, Mapping) else {}
    settings = backends.get("mistral", {}) if isinstance(backends, Mapping) else {}
    return dict(settings) if isinstance(settings, Mapping) else {}


def _free_tier_settings(config: Mapping[str, Any]) -> dict[str, Any]:
    value = _mistral_settings(config).get("free_tier", {})
    return dict(value) if isinstance(value, Mapping) else {}


def _positive_float(value: Any, default: float) -> float:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return default
    return parsed if math.isfinite(parsed) and parsed > 0 else default


def _nonnegative_float(value: Any, default: float) -> float:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return default
    return parsed if math.isfinite(parsed) and parsed >= 0 else default


def free_tier_enabled(config: Mapping[str, Any]) -> bool:
    """Return whether the project should enforce the local free-tier guard."""
    value = _free_tier_settings(config).get("enabled", False)
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "on"}
    return bool(value)


def allowed_pages(config: Mapping[str, Any]) -> int:
    """Calculate the monthly page cap after applying the configured reserve."""
    settings = _free_tier_settings(config)
    allowance = _positive_float(
        settings.get("monthly_allowance_usd"), DEFAULT_MONTHLY_ALLOWANCE_USD
    )
    price = _positive_float(
        settings.get("ocr_price_per_1000_pages_usd"),
        DEFAULT_OCR_PRICE_PER_1000_PAGES_USD,
    )
    margin = _nonnegative_float(
        settings.get("safety_margin_usd"), DEFAULT_SAFETY_MARGIN_USD
    )
    return max(0, math.floor(max(0.0, allowance - margin) * 1000 / price))


def usage_ledger_path(config: Mapping[str, Any]) -> Path:
    """Resolve the ledger path without ever including credentials in it."""
    raw_path = _free_tier_settings(config).get("usage_ledger", DEFAULT_USAGE_LEDGER)
    path = Path(str(raw_path or DEFAULT_USAGE_LEDGER)).expanduser()
    return path if path.is_absolute() else Path.cwd() / path


def _load_ledger(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"schema_version": LEDGER_SCHEMA_VERSION, "months": {}}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise RuntimeError(
            f"Mistral usage ledger is unreadable; refusing to send OCR requests: {path}"
        ) from exc
    if not isinstance(value, dict) or value.get("schema_version") != LEDGER_SCHEMA_VERSION:
        raise RuntimeError(
            f"Mistral usage ledger has an unsupported format; refusing to send OCR requests: {path}"
        )
    months = value.get("months")
    if not isinstance(months, dict):
        raise RuntimeError(
            f"Mistral usage ledger has no valid monthly data; refusing to send OCR requests: {path}"
        )
    return value


def _integer(value: Any) -> int:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return 0
    return max(0, parsed)


def _write_status(
    output_dir: Optional[Path],
    *,
    status: str,
    month: str,
    requested_pages: int,
    reserved_before: int,
    reserved_after: int,
    cap_pages: int,
    ledger_path: Path,
    error: Optional[str] = None,
) -> None:
    if output_dir is None:
        return
    payload = {
        "schema_version": LEDGER_SCHEMA_VERSION,
        "status": status,
        "month": month,
        "requested_pages": requested_pages,
        "reserved_pages_before": reserved_before,
        "reserved_pages_after": reserved_after,
        "allowed_pages": cap_pages,
        "remaining_pages": max(0, cap_pages - reserved_after),
        "ledger": str(ledger_path),
    }
    if error:
        payload["error"] = error
    atomic_write_text(
        Path(output_dir) / "mistral_budget.json",
        json.dumps(payload, ensure_ascii=False, indent=2),
    )


def reserve_pages(
    config: Mapping[str, Any],
    page_count: int,
    *,
    source_sha256: str,
    secondary_config_sha256: str,
    output_dir: Optional[Path] = None,
) -> Optional[dict[str, Any]]:
    """Reserve Mistral OCR pages before any remote request is made.

    The ledger deliberately counts reservations rather than successful calls.
    A failed or interrupted request is not rolled back because its billing
    outcome is unknown; this keeps the local guard conservative.
    """
    if not free_tier_enabled(config):
        return None
    try:
        requested_pages = int(page_count)
    except (TypeError, ValueError) as exc:
        raise ValueError("Mistral OCR page count must be an integer") from exc
    if requested_pages <= 0:
        return None

    ledger_path = usage_ledger_path(config)
    month = date.today().strftime("%Y-%m")
    cap_pages = allowed_pages(config)

    with _LEDGER_LOCK:
        ledger = _load_ledger(ledger_path)
        months = ledger["months"]
        month_data = months.setdefault(month, {})
        if not isinstance(month_data, dict):
            raise RuntimeError(
                f"Mistral usage ledger month entry is invalid; refusing to send OCR requests: {ledger_path}"
            )
        reserved_before = _integer(month_data.get("reserved_pages"))
        reserved_after = reserved_before + requested_pages
        if reserved_after > cap_pages:
            message = (
                "Mistral OCR free-tier guard blocked this request: "
                f"{requested_pages} pages requested, {max(0, cap_pages - reserved_before)} pages remain "
                f"for {month} (cap {cap_pages} pages, including the configured safety margin)."
            )
            _write_status(
                output_dir,
                status="blocked",
                month=month,
                requested_pages=requested_pages,
                reserved_before=reserved_before,
                reserved_after=reserved_before,
                cap_pages=cap_pages,
                ledger_path=ledger_path,
                error=message,
            )
            raise MistralBudgetExceeded(message)

        month_data["reserved_pages"] = reserved_after
        month_data["updated_at"] = datetime.now(timezone.utc).isoformat()
        reservations = month_data.setdefault("reservations", [])
        if not isinstance(reservations, list):
            raise RuntimeError(
                f"Mistral usage ledger reservations are invalid; refusing to send OCR requests: {ledger_path}"
            )
        reservations.append(
            {
                "pages": requested_pages,
                "source_sha256": str(source_sha256),
                "secondary_config_sha256": str(secondary_config_sha256),
                "reserved_at": datetime.now(timezone.utc).isoformat(),
            }
        )
        ledger_path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(
            ledger_path,
            json.dumps(ledger, ensure_ascii=False, indent=2),
        )

    _write_status(
        output_dir,
        status="reserved",
        month=month,
        requested_pages=requested_pages,
        reserved_before=reserved_before,
        reserved_after=reserved_after,
        cap_pages=cap_pages,
        ledger_path=ledger_path,
    )
    return {
        "month": month,
        "requested_pages": requested_pages,
        "reserved_pages": reserved_after,
        "allowed_pages": cap_pages,
        "remaining_pages": max(0, cap_pages - reserved_after),
        "ledger_path": str(ledger_path),
    }


__all__ = [
    "DEFAULT_MONTHLY_ALLOWANCE_USD",
    "DEFAULT_OCR_PRICE_PER_1000_PAGES_USD",
    "DEFAULT_SAFETY_MARGIN_USD",
    "MistralBudgetExceeded",
    "allowed_pages",
    "free_tier_enabled",
    "reserve_pages",
    "usage_ledger_path",
]
