"""
TOC Tree data structures.

Provides TOCNode for representing recursive book structure.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass
class TOCNode:
    """
    Represents a node in the recursive TOC tree.

    Each node corresponds to a chapter/section/subsection in the book.
    The tree structure allows arbitrary depth.
    """
    title: str
    level: int
    start_page: int
    end_page: int
    children: List['TOCNode'] = field(default_factory=list)

    # Populated after boundary verification
    # Contains: start_line (int), end_line (int) - for mid-page splits
    boundary_info: Optional[Dict] = None

    # For notes chapters
    chapter_type: Optional[str] = None  # "notes" or None

    # Estimated token count (populated during processing)
    estimated_tokens: int = 0

    # Whether this node was auto-generated by gap filling
    gap_filled: bool = False

    def is_leaf(self) -> bool:
        """Check if this node has no children."""
        return len(self.children) == 0

    def get_all_leaves(self) -> List['TOCNode']:
        """Get all leaf nodes under this node (including self if leaf)."""
        if self.is_leaf():
            return [self]

        leaves = []
        for child in self.children:
            leaves.extend(child.get_all_leaves())
        return leaves

    def get_toc_path(self, ancestors: List[str] = None) -> List[str]:
        """Get the full TOC path from root to this node."""
        if ancestors is None:
            ancestors = []
        return ancestors + [self.title]

    def to_dict(self) -> Dict:
        """Convert to dictionary for serialization."""
        result = {
            "title": self.title,
            "level": self.level,
            "start_page": self.start_page,
            "end_page": self.end_page,
        }
        if self.chapter_type:
            result["type"] = self.chapter_type
        if self.gap_filled:
            result["gap_filled"] = self.gap_filled
        if self.children:
            result["children"] = [child.to_dict() for child in self.children]
        if self.boundary_info:
            result["boundary_info"] = self.boundary_info
        if self.estimated_tokens:
            result["estimated_tokens"] = self.estimated_tokens
        return result

    @classmethod
    def from_dict(cls, data: Dict) -> 'TOCNode':
        """Create TOCNode from dictionary."""
        # Validate required fields
        if 'start_page' not in data or 'end_page' not in data:
            from loguru import logger
            logger.warning(f"Skipping invalid TOC entry (missing page info): {data.get('title', 'unknown')}")
            return None

        node = cls(
            title=data['title'],
            level=data.get('level', 1),
            start_page=data['start_page'],
            end_page=data['end_page'],
            chapter_type=data.get('type')
        )

        children_data = data.get('children', [])
        if children_data:
            children = [cls.from_dict(child) for child in children_data]
            node.children = [c for c in children if c is not None]  # Filter invalid

        if 'boundary_info' in data:
            node.boundary_info = data['boundary_info']
        if 'estimated_tokens' in data:
            node.estimated_tokens = data['estimated_tokens']
        if data.get('gap_filled'):
            node.gap_filled = True

        return node


def dict_list_to_toc_tree(chapters_data: List[Dict]) -> List[TOCNode]:
    """Convert a list of chapter dictionaries to TOCNode tree."""
    nodes = [TOCNode.from_dict(chapter) for chapter in chapters_data]
    return [n for n in nodes if n is not None]  # Filter invalid entries
